#+title: Sean Gallagher — Résumé
#+html_head_extra: <link rel="stylesheet" href="/styles/resume.css" type="text/css" />
* Summary
:PROPERTIES:
:html_container_class: summary
:custom_id: summary
:END:
- @@html: <span class="fas fa-phone"></span>@@ @@html:<a href="tel:+15183626816">518.362.6816</a>@@
- @@html: <span class="fas fa-envelope-open"></span>@@ [[mailto:seangllghr@gmail.com][seangllghr@gmail.com]]
- @@html: <span class="fab fa-github"></span>@@ [[https://github.com/seangllghr][seangllghr]]
- @@html: <span class="fas fa-folder"></span>@@ [[https://seangllghr.github.io][seangllghr.github.io]]
# - @@html: <span class="fas fa-map-marker-alt"></span>@@ 15 Swatling Rd. Apt. 1, Latham, NY 12110

Dedicated, self-motivated full-stack developer with an interest in
web technologies, visual design, and open source software. 11 years experience
in customer-facing and instructional positions with 7 years experience leading
teams of 5--50 people
* Education
:PROPERTIES:
:html_container_class: education
:custom_id: education
:END:
** Bachelor of Science, Computer Science
- Focus :: Concentration in Software Engineering
- Institution :: Southern New Hampshire University, Manchester, NH. April 2022 (Awaiting Conferral)
** Associates of Applied Arts and Sciences, Adventure Sports Leadership and Management
- Focus :: Dual Concentration in Snowsports Instruction and Challenge Course Facilitation & Management\\
- Institution :: State University of New York Adirondack, Queensbury, NY. 2012
* Technical Skills
:PROPERTIES:
:custom_id: skills
:html_container_class: skills
:END:
** Languages:
- Javascript/Typescript
- HTML
- CSS
- Python
- Java
- C/C++
- Bash
- @@html: <span class="latex">L<span>a</span>T<span>e</span>X</span>@@
** Tools and Technologies
- Node.js
- Angular
- Nest.js
- JSON
- Adobe Illustrator
- Adobe InDesign
** Operating Systems
- Linux
- Windows
* Experience
:PROPERTIES:
:html_container_class: experience
:custom_id: experience
:END:
** Program Director
:PROPERTIES:
:html_container_class: position
:END:
- Period :: Summer Seasonal, 2017--2019
- Employer :: Camp Wakpominee, Twin Rivers Council, Boy Scouts of America
- Summary ::
  - Led a team of 10 program area directors responsible for a total of more than
    50 program staff.
  - Designed forms, schedule handouts, and other hard copy documents
    related to camp program and activities,
    using proprietary design tools and open-source alternatives,
    including HTML/CSS-to-PDF toolchains,
    Microsoft Office,
    Adobe Illustrator,
    and Adobe InDesign.
  - Automated publication of a daily newsletter, using Node.js to ingest a
    Markdown/plaintext feature article source and JSON daily schedule to build an
    HTML file for PDF conversion.
  - Installed and configured a dedicated Linux server that handled weekly
    paperwork and provision of common network resources within the camp office.
  - Handled routine IT configuration and troubleshooting tasks for the camp
    office's heterogeneous network environment, including Linux, Windows, and
    MacOS systems.
** Snow Pro
:PROPERTIES:
:html_container_class: position
:END:
- Period :: Winter Seasonal, 2013--19
- Employer :: Ski and Snowboard Schools of Aspen/Snowmass, Aspen Skiing Company
- Summary ::
  - Instructed an international clientele of children and adults in downhill
    skiing skills
  - Facilitated guest interactions with other Aspen Skiing Company departments and
    outside service providers, including lesson sales and ticketing, rentals,
    dining, and transportation services
** Aquatics Director
:PROPERTIES:
:html_container_class: position
:END:
- Period :: Summer Seasonal 2016
- Employer :: Henderson Scout Reservation, Leatherstocking Council, Boy Scouts of America
- Summary ::
  - Managed a team of four aquatics instructors responsible for lifeguard coverage and skill instruction
  - Led weekly off-site canoe trips of 30--50 Scouts
# - Developed and deployed an intranet portal for distributing materials for Merit
#   Badge instruction
** Aquatics Director
:PROPERTIES:
:html_container_class: position
:END:
- Period :: Summer Seasonal 2013--2015
- Employer :: Camp Wakpominee, Twin Rivers Council, Boy Scouts of America
* Volunteer Experience
:PROPERTIES:
:html_container_class: volunteer
:custom_id: volunteer
:END:
** Committee Member
:PROPERTIES:
:html_container_class: position
:END:
- Period :: 2013--Present
- Organization :: Council Aquatics Committee, Twin Rivers Council, Boy Scouts of America
- Summary ::
  - Kept and published minutes for regular meetings
    using @@html: <span class="latex">L<span>a</span>T<span>e</span>X</span>@@
    and Emacs org-mode
  - Designed, using Adobe Illustrator, a patch recognizing dedication to aquatics programs
  - Facilitated an annual pre-camp training program for aquatics staff from both
    council camps
** Aquatics Section Faculty
:PROPERTIES:
:html_container_class: position
:END:
- Period :: June 2015--June 2019
- Organization :: National Camping School Adirondack Section, Boy Scouts of America
- Summary ::
  - Taught water rescue, swimming, and boating skills to aquatics director
    candidates
  - Trained candidates in crucial managerial soft skills, including interpersonal
    interaction, conflict resolution, and effective teaching
* Languages Spoken
:PROPERTIES:
:html_container_class: languages
:custom_id: languages
:END:
- English :: Native Speaker
- Spanish :: Fluent
# - Portuguese :: Basic
