name: Publish to Github Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Install Emacs
        run: sudo apt install emacs-nox --yes
      - name: Build
        run: bash build
      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: public
